cloud_filter_chain:
    - name: RobotBodyFilter
      type: robot_body_filter/RobotBodyFilterPointCloud2
      params:
        frames/sensor: 'kinect2_link'
        frames/filtering: 'kinect2_link'
        frames/output: 'kinect2_link'
        body_model/robot_description_param: 'robot_description'

      filter/do_clipping: True
      filter/do_contains_test: True
      filter/do_shadow_test: False

      sensor/point_by_point: False
      sensor/min_distance: 0.01
      sensor/max_distance: 1.5

      body_model/inflation/scale: 1.1
      body_model/inflation/padding: 0.03

      transforms/buffer_length: 15.0
      transforms/timeout/reachable: 0.2
      transforms/timeout/unreachable: 0.2

      bounding_sphere/compute: False
      bounding_box/compute: False
      oriented_bounding_box/compute: False
      local_bounding_box/compute: False
      debug/pcl/inside: True
      debug/pcl/clip: True
      debug/pcl/shadow: False
      debug/marker/contains: False
      debug/marker/shadow: False
